// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qkgkhsqfpseeljhasirb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrZ2toc3FmcHNlZWxqaGFzaXJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NjM2MDIsImV4cCI6MjA2MzQzOTYwMn0.DR22SdNqi8uQ1AjUmufE1ctQMLc79XjRTI2AbTsG9w8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);